import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { CheckCircle2, ExternalLink, Fingerprint, ShieldAlert, ShieldCheck } from 'lucide-react';
import { apiFetch } from '../lib/api';
import { HashBadge } from '../components/ui/HashBadge';
import { Skeleton } from '../components/ui/Skeleton';

type PublicRecord = { id:string; integrity:string; evidence_sha256:string|null; audit_chain:{valid:boolean;checked_events:number;message:string}; summary:{project:string;agreement_version:number|null;evidence_version:number|null;results:Array<{kpi:string;claimed:number|null;recomputed:number|null;outcome:string}>;technical_suitability:string|null;procurement_route:string}; disclaimer:string };
export default function PublicVerifyPage(){
  const {id=''}=useParams();const [record,setRecord]=useState<PublicRecord|null>(null);const [error,setError]=useState('');
  useEffect(()=>{let active=true;apiFetch(`/api/verify/${encodeURIComponent(id)}`).then(async res=>{const body=await res.json();if(!res.ok)throw new Error(body.detail||'Verification record not found.');if(active)setRecord(body);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Unable to verify record.');});return()=>{active=false}},[id]);
  return <main className='min-h-screen bg-[#f7f5ef] px-5 py-10 text-slate-900'><div className='mx-auto max-w-3xl space-y-6'><Link to='/' className='text-sm font-semibold text-slate-600'>← PilotProof</Link><header className='rounded-3xl border border-slate-200 bg-white p-7 shadow-sm'><div className='flex items-center gap-3'><span className='rounded-xl bg-emerald-50 p-3 text-emerald-700'><ShieldCheck size={24}/></span><div><p className='text-xs uppercase tracking-[.17em] text-slate-500'>Public record verification</p><h1 className='mt-1 text-2xl font-semibold'>{record?.summary.project||'Pilot passport'}</h1></div></div><p className='mt-5 rounded-xl bg-slate-50 p-3 text-xs text-slate-600'>{record?.disclaimer||'Structured project record. Not a government certification.'}</p></header>
    {error&&<div role='alert' className='flex items-center gap-2 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800'><ShieldAlert size={17}/>{error}</div>}
    {!record&&!error?<Skeleton className='h-56'/>:record&&<><section className={`rounded-2xl border p-5 ${record.integrity==='Verified'&&record.audit_chain.valid?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50'}`}><div className='flex items-center gap-2 font-semibold'>{record.integrity==='Verified'?<CheckCircle2 size={18}/>:<ShieldAlert size={18}/>}Evidence integrity: {record.integrity}</div><p className='mt-1 text-xs opacity-75'>{record.audit_chain.message} · {record.audit_chain.checked_events} audit events checked.</p>{record.evidence_sha256&&<div className='mt-3 flex items-center gap-2 text-xs'><Fingerprint size={14}/>File fingerprint<HashBadge value={record.evidence_sha256}/></div>}</section>
    <section className='rounded-2xl border border-slate-200 bg-white p-5'><h2 className='font-semibold'>Redacted project summary</h2><div className='mt-3 grid grid-cols-2 gap-3 text-sm'><div className='rounded-xl bg-slate-50 p-3'><span className='text-xs text-slate-500'>Agreement version</span><p className='mt-1 font-medium'>{record.summary.agreement_version??'—'}</p></div><div className='rounded-xl bg-slate-50 p-3'><span className='text-xs text-slate-500'>Evidence version</span><p className='mt-1 font-medium'>{record.summary.evidence_version??'No upload'}</p></div><div className='rounded-xl bg-slate-50 p-3'><span className='text-xs text-slate-500'>Technical suitability</span><p className='mt-1 font-medium'>{record.summary.technical_suitability||'Not assessed'}</p></div><div className='rounded-xl bg-slate-50 p-3'><span className='text-xs text-slate-500'>Procurement route</span><p className='mt-1 font-medium'>{record.summary.procurement_route}</p></div></div><div className='mt-4 space-y-2'>{record.summary.results.map(item=><div key={item.kpi} className='flex flex-wrap justify-between gap-2 rounded-lg border border-slate-100 p-3 text-sm'><strong>{item.kpi}</strong><span>{item.claimed??'—'} claimed → {item.recomputed??'—'} recomputed</span><span className='font-medium capitalize'>{item.outcome.replace('_',' ')}</span></div>)}</div></section><p className='flex items-center gap-1 text-xs text-slate-500'>Read-only public summary · <a href={`/passport/${encodeURIComponent(id)}`} className='font-medium text-amber-700'>Open project passport <ExternalLink size={12}/></a></p></>}
  </div></main>;
}
